# === Build Stage ===
FROM node:22-alpine AS builder
COPY good-food-contracts /good-food-contracts
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

# === Production Stage ===
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/prisma ./prisma
EXPOSE 8080
CMD ["node", "dist/src/server.js"]
